project:
  type: website

website:
  site-url: https://stat156.berkeley.edu/fall-2024/
  google-analytics: G-QR6SS0MKFJ
  sidebar:
    style: docked
    title: "Stat 156"
    logo: assets/stat_bear.png
    tools:
      - icon: github
        href: https://github.com/berkeley-stat156/fall-2024/
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: syllabus.qmd
        text: Syllabus
      - href: staff.qmd
        text: Staff
      - href: calendar.qmd
        text: Calendar
      # - section: "Units"
      #   contents:
      #     - units/unit1.qmd
      #     - units/unit2.ipynb
      #     - units/unit3.qmd
      # - href: data.qmd
      #   text: Datasets
      - href: license.qmd
        text: License
          

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true



