---
title: "Statistics 156/256: Causal Inference"
subtitle: "UC Berkeley, Fall 2024"
listing:
  # - id: schedule
  #   template: assets/schedule.ejs
  #  contents: schedule.yml
  - id: buttons
    template: assets/buttons.ejs
    contents: buttons.yml
---

::: {#buttons}
:::




::: {.callout-note title="Welcome to Week 1 of Stat 156"}
Office hours on 8/29 will be in Evans 355 from 4-5 pm.
:::

::: {.callout-note title="Syllabus"}
The [syllabi](https://stat156.berkeley.edu/fall-2024/syllabus.html) are now available for 156 and 256.
:::

::: {.callout-note title="Readings week 1"}
The reading for the first lecture is Chapter 1 of the textbook _A first course in causal inference_ by Peng Ding.
A preprint of the textbook is available on [arXiv](https://arxiv.org/pdf/2305.18793). The book is available 
in print [here](https://www.routledge.com/A-First-Course-in-Causal-Inference/Ding/p/book/9781032758626). 
 Add promotion code JSM24 for additional discount (good thru end of
September). 
:::

::: {.callout-note title="Readings week 2"}
The reading for the second lecture is Chapter 2 of _A first course in causal inference_.

The readings for the third lecture are 

1. Section 2.1 of the textbook _Causal inference: what if_ by 
James M. Robins and Miguel A. Hernán. Available [online](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/).
2. Chapter 3 of _A first course in causal inference_.
:::

::: {.callout-note title="Readings week 3"}
The reading for the fourth lecture is Chapters 4-6 of _A first course in causal inference_.

The readings for the fifth lecture is Chapters 7-9 of _A first course in causal inference_.
:::

::: {.callout-note title="Readings week 4"}
The reading for the 9/17 lecture is
1. Chapter 3 of  _Causal inference: what if_.
2. Chapter 10 of _A first course in causal inference_.

The readings for the 9/19 lecture are
1. Section 2.4 of  _Causal inference: what if_.
2. Chapters 11-12 of _A first course in causal inference_.
:::

::: {.callout-note title="Zoom lecture on 9/10"}
Reminder that we will be meeting on Zoom for the lecture on September 10th.
:::

